### ISSUE TITLE
Nieprawidłowe wyświetlanie przycisków w edytorze

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#14]
![zaznaczenie_491](https://cloud.githubusercontent.com/assets/3618479/14942755/e4054d1a-0fc6-11e6-91ed-1d1fdd9e503a.png)
Te czerwone z prawej

**Comment by ad-m** [comment]
Oszust
![zaznaczenie_503](https://cloud.githubusercontent.com/assets/3618479/14997793/d135fd22-1180-11e6-8e76-76b1ff79f6fe.png)

**Comment by mik-laj** [comment]
![selection_003](https://cloud.githubusercontent.com/assets/12058428/15001393/6ce0591e-1197-11e6-9038-77c2ce4a320f.png)
