### ISSUE TITLE
TinyMCE w polu edycji opisu w monitoringu

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/bliski_publikator#15]

**Comment by mik-laj** [comment]
Done via #c207ad2540821d8bf1e8b1ad41275400663a31fa

**Comment by ad-m** [comment]
![zaznaczenie_506](https://cloud.githubusercontent.com/assets/3618479/14999270/7912435a-1188-11e6-9b91-a8b802c8557a.png)

**Comment by mik-laj** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/12058428/15001306/bfdd5762-1196-11e6-8323-ef05807ac92d.png)

**Comment by ad-m** [comment]
Otwieram ponownie tylko po to, aby Cię postraszyć.
