### ISSUE TITLE
Style sekcji użytkownika

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#23]
Ścieżka `/bliski_publikator/templates/account`` i pokrewne wraz z tłumaczeniami. 

Przypisuje do @mik-laj, ale powinien to zrobić ten kto ma pierwszy czas.

**Comment by mik-laj** [comment]
Tłumaczenie nie sprawdziłem. Resztę sprawdziłem i poprawiłem przez #8dcf8c5

**Comment by ad-m** [comment]
Przyciski trzeba oscylować.
