### ISSUE TITLE
API api/monitoring/1

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/bliski_publikator#26]
Szanowny, 
Brakuje API odpowiedzialnego za zwracanie danych o monitoringu zgodnie z API: 
/bliski_publikator/templates/api/monitoring-1-get-ok.json
Z wyrazami szacunku

**Comment by ad-m** [comment]
http://localhost:8000/monitorings/2/api

**Comment by ad-m** [comment]
By e777ec4
