### ISSUE TITLE
Stopka

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#27]
![stopka](https://cloud.githubusercontent.com/assets/3618479/14984692/50a52e12-1144-11e6-9605-615891133977.jpg)

**Comment by mik-laj** [comment]
Skąd te obrazki mogę ukraść?

**Comment by ad-m** [comment]
Musisz napisać do Zdanowicz.

W dniu wtorek, 3 maja 2016 Kamil Breguła notifications@github.com
napisał(a):

> Skąd te obrazki mogę ukraść?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/watchdogpolska/bliski_publikator/issues/27#issuecomment-216589160

## 

Wysłano z Gmaila na komórki

**Comment by mik-laj** [comment]
A patroni medialni też nam się chyba zmienią, bo to inny projekt :-/

**Comment by ad-m** [comment]
Napisz do Zdanowicz.

**Comment by mik-laj** [comment]
![loga7](https://cloud.githubusercontent.com/assets/12058428/15093592/dff35d8c-148c-11e6-87e4-b9c576e87bca.png)

**Comment by mik-laj** [comment]
Czy na pewno stopka?

**Comment by mik-laj** [comment]
Done via: f028cd67df66555a6b19aaaf3db1bec268ad3d54
