### ISSUE TITLE
Dodać tłumaczenie etykiet w kreatorze ankiet

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#30]
![zaznaczenie_505](https://cloud.githubusercontent.com/assets/3618479/14999219/212e0f84-1188-11e6-9b71-1539c11e8a16.png)

**Comment by mik-laj** [comment]
![1_001](https://cloud.githubusercontent.com/assets/12058428/15000560/ff11052e-1190-11e6-8d3a-cca2e52e365e.png)
