### ISSUE TITLE
Safe na opisie monitoringu w solverze

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#40]
![zaznaczenie_516](https://cloud.githubusercontent.com/assets/3618479/15036379/5e7ecbb0-128e-11e6-8c69-ceb9c87fa1f3.png)

**Comment by mik-laj** [comment]
Done via: https://github.com/watchdogpolska/bliski_publikator/commit/16d127a3056e78cd04e4e45a7c8aba376bb1f3cf
