### ISSUE TITLE
Po dodaniu monitoringu żadnego okna i przekierowanie do strony monitoringu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#49]
- [x] zmienić skrypt JavaScript - @mik-laj 
- [ ] sprawdzić czy jest Flash messages - @ad-m

**Comment by ad-m** [comment]
Po tym wnioskuje, że ANI RAZU nie wypełniłeś tego na spokojnie, aby ocenić usability :-1: :crying_cat_face:

**Comment by ad-m** [comment]
Jakby było mało to opcje wyboru się nie zapisywały. Były po prostu zepsute. 85923cbc2eda923a75c8ba28d33f6a544dd052e1 To powinieneś sprawdzić. Miałeś na to DWA dni. 😢

**Comment by mik-laj** [comment]
https://github.com/watchdogpolska/bliski_publikator/commit/c2b3e7a5d611d5159bbf68e04c461bee69a1f712

**Comment by mik-laj** [comment]
O jaki skrypt Javascript ci chodzi?

**Comment by ad-m** [comment]
To co zmieniłeś. Ja tam nie wnikam czy to Angular, czy jeszcze gdzieś indziej - JavaScript.
