### ISSUE TITLE
Skasować tego JSONa z widoku wypełniania ankiety

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#62]
![near-perfect_bulletin _-_2016-05-23_02 26 24](https://cloud.githubusercontent.com/assets/3618479/15457670/c684ddd2-208d-11e6-8a23-634f42e75d7d.png)

**Comment by Dzakus** [comment]
Już nie jest skasowany?

**Comment by ad-m** [comment]
Chyba jest, u mnie nie było. Trzeba sprawdzić i zamknąc.
