### ISSUE TITLE
Wygląd formularza logowania

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#69]
https://kontrola.siecobywatelska.pl/accounts/login/?next=/monitorings/monitoring-spolek-komunalnych/miejskie-przedsiebiorstwo-wodociagow/%7Eanswers

![zaznaczenie_583](https://cloud.githubusercontent.com/assets/3618479/15489655/026a0744-2162-11e6-8e37-f81cfe3bf0dc.png)

**Comment by ad-m** [comment]
Analogicznie formularz rejestracji:
![zaznaczenie_584](https://cloud.githubusercontent.com/assets/3618479/15489662/1b352254-2162-11e6-9107-4adc15c2ffe5.png)

**Comment by Dzakus** [comment]
Tutaj templatka się nie ładuje. Wcześniej było ładnie. Ten formularz generuje się z znaczników p zamiast div.

**Comment by ad-m** [comment]
Zrobisz to, czy ja? Niezmiennie co do przyczyny naprawić trzeba.

**Comment by mik-laj** [comment]
It's related to django.  I can not help you. I assign to you.

**Comment by mik-laj** [comment]
Od kiedy dwie osoby mogą być przypisane do jednego issues? Kiedy to  się zmieniło?
