### ISSUE TITLE
Update view to looks like http://siecobywatelska.pl/co-robimy/ #}

### ISSUE THREAD

**Issue by FreeHooks** [watchdogpolska/bliski_publikator#7]
File: https://github.com/watchdogpolska/bliski_publikator/blob/0d3e46fb8f4a5420cc87af1ddbbeaddac0091cb6/bliski_publikator/monitorings/templates/monitorings/monitoring_detail.html#L30

**Comment by mik-laj** [comment]
Close. Duplicate: https://github.com/watchdogpolska/bliski_publikator/issues/11

**Comment by ad-m** [comment]
![zaznaczenie_498](https://cloud.githubusercontent.com/assets/3618479/14968380/ae2fdbfa-10bc-11e6-96da-c7cffe471460.png)
vs.
![zaznaczenie_500](https://cloud.githubusercontent.com/assets/3618479/14968394/c876a250-10bc-11e6-831a-1d8b2be6484c.png)

Jest różnica. #11 to lista obiektów w treści, a tutaj lista obiektów w menu nawigacyjnym
