### ISSUE TITLE
Zablokować przeskakiwanie na górę strony przy dodawaniu pytania

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#77]

**Comment by mik-laj** [comment]
Wiem, że to jest, ale nie rozumiem dlaczego tak się dzieje. Przypuszczam, że dlatego, że przez moment przeglądarka myśli, że dokument jest zbyt krótki, ponieważ wszystkie pytania są kasowane, a potem dodawane.

**Comment by ad-m** [comment]
To przypisz label enhacement i zostaw, chyba że CSSem sfałszujesz wysokość
na chwilę...

Wysłano z urządzenia mobilnego.
26 maj 2016 12:12 "Kamil Breguła" notifications@github.com napisał(a):

**Comment by mik-laj** [comment]
Sfałszować będzie tutaj trudno.
