### ISSUE TITLE
Ankieta się nie wypełnia

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#79]
https://kontrola.siecobywatelska.pl/monitorings/msk/zaklad-inzynierii-miejskiej/~answers

**Comment by Dzakus** [comment]
https://kontrola.siecobywatelska.pl/accounts/login/?next=/monitorings/msk/zaklad-inzynierii-miejskiej/~answers strona logowania jest nie ostylowana. Coś chyba źle się wczytuje
