### ISSUE TITLE
Strona główna - zbudować elastyczną

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/bliski_publikator#82]

**Comment by mik-laj** [comment]
W jaki sposób strona główna ma być elastyczna?

**Comment by ad-m** [comment]
Tam, gdzie teraz jest tekst statyczny ma być django-tinycontent.

Wysłano z urządzenia mobilnego.
29 maj 2016 11:28 AM "Kamil Breguła" notifications@github.com napisał(a):
