### ISSUE TITLE
Czy przed rozwiązaniem ankiety ma się wyświetlać opis monitoringu?

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/bliski_publikator#87]
Dzień dobry.

Wydaje mi się to trochę dziwne. Jak ktoś już wszedł to już raczej wie czym się zajmuje. Może to wprowadzać w zakłopotanie, jeśli dostaje ciągle te same teksty. Może powodować to nie czytanie wszystkiego uważnie. Może tam powinien być dodany inny tekst? 

Z wyrazami szacunku

**Comment by ad-m** [comment]
Tak, inny tekst. Doda pole w modelu Monitoring i nad ankietą je wyświetl. Taka instrukcja do ankiety.

**Comment by mik-laj** [comment]
Ok. Pracuje nad tym. Na razie walczę z bugiem, bo pól wyboru nie zapisuje mimo, że odpowiedź wysyłam.
