### ISSUE TITLE
Nie zapisuje odpowiedz z pytań wyboru

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/bliski_publikator#88]
Szanowny. 
1. Utworzyłem formularz przez aplikacje i w wyniku tego wysłał się taki JSON: http://pastebin.com/MTZXAHZE
2. Przypisałem instytucje
3. Rozwiązałem ankietę, co skutkowało takiemu JSONowi: http://pastebin.com/PvHgeqVg
4. W wyniku nie widać odpowiedzi tylko do pytania wyboru. Pytania tekstowe i pytania długie tekstowe się zapisują

Chciałbym, żeby wszystkie dane się zapisywały. 

Z wyrazami szacunku.

**Comment by ad-m** [comment]
To jednak mamy pytania wielokrotnego wyboru?

2016-05-29 12:03 GMT+02:00 Kamil Breguła notifications@github.com:

**Comment by mik-laj** [comment]
Nie wielokrotnego wyboru. Pomyłka. Wybór z listy.
